version: "3.8"

services:

  webservice:
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    container_name: webservice
    environment:
      - PORT=5000
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_SERVER=mongodb
      - MONGO_INITDB_DATABASE=sampledb
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    restart: unless-stopped
    volumes:
      - ./app:/var/www
    links:
      - mongodb
    networks:
      - mongo_net

  #webserver:
    #build:
      #context: nginx
      #dockerfile: Dockerfile
    #container_name: webserver
    #restart: unless-stopped
    #environment:
      #APP_ENV: "prod"
      #APP_NAME: "webserver"
      #APP_DEBUG: "false"
      #SERVICE_NAME: "webserver"
    #ports:
      #- "80:80"
      #- "443:443"
    #volumes:
      #- nginxdata:/var/log/nginx
    #depends_on:
      #- webservice
    #networks:
      #- mongo_net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped 
    ports:
      - 27017:27017 
    environment:
      - MONGO_INITDB_DATABASE=sampledb
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGODB_DATA_DIR=/data/db
      - MONDODB_LOG_DIR=/dev/null
    volumes:
      - ./mongo-entrypoint/initdb.js:/docker-entrypoint-initdb.d/initdb.js:ro
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - mongo_net

volumes:
  nginxdata:
    driver: local
  mongodb:
    driver: local
  mongoconfig:
    driver: local

networks:
  mongo_net:
    driver: bridge