version: "3.8"

services:

  webservice:
    build: .
    ports:
      - 5000:5000
    container_name: flask-app
    environment:
      - FLASK_ENV=production
      - PORT=5000
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_SERVER=mongodb
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - mongo_net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped 
    ports:
      - 27017:27017
    command: mongod --auth
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGODB_DATA_DIR=/data/db
      - MONDODB_LOG_DIR=/dev/null
    volumes:
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - mongo_net

volumes:
  mongodb:
  mongoconfig:

networks:
  mongo_net:
    driver: bridge